/* 
 * FairWayBank
 *
 * FairWayBank Accounts + Transactions API
 *
 * OpenAPI spec version: v1
 * Contact: development@bizfitech.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// TransactionViewModel
    /// </summary>
    [DataContract]
    public partial class TransactionViewModel :  IEquatable<TransactionViewModel>, IValidatableObject
    {
        /// <summary>
        /// Indicates whether the transaction is a credit or a debit entry.
        /// </summary>
        /// <value>Indicates whether the transaction is a credit or a debit entry.</value>
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum NUMBER_0 for value: 0
            /// </summary>
            
            NUMBER_0 = 0,
            
            /// <summary>
            /// Enum NUMBER_1 for value: 1
            /// </summary>
            
            NUMBER_1 = 1
        }

        /// <summary>
        /// Indicates whether the transaction is a credit or a debit entry.
        /// </summary>
        /// <value>Indicates whether the transaction is a credit or a debit entry.</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionViewModel" /> class.
        /// </summary>
        /// <param name="Amount">The amount of the transaction.</param>
        /// <param name="TransactionInformation">The transaction description.</param>
        /// <param name="Type">Indicates whether the transaction is a credit or a debit entry..</param>
        /// <param name="BookedDate">The date the transaction was booked.</param>
        public TransactionViewModel(double? Amount = default(double?), string TransactionInformation = default(string), TypeEnum? Type = default(TypeEnum?), DateTime? BookedDate = default(DateTime?))
        {
            this.Amount = Amount;
            this.TransactionInformation = TransactionInformation;
            this.Type = Type;
            this.BookedDate = BookedDate;
        }
        
        /// <summary>
        /// The amount of the transaction
        /// </summary>
        /// <value>The amount of the transaction</value>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public double? Amount { get; set; }

        /// <summary>
        /// The transaction description
        /// </summary>
        /// <value>The transaction description</value>
        [DataMember(Name="transactionInformation", EmitDefaultValue=false)]
        public string TransactionInformation { get; set; }


        /// <summary>
        /// The date the transaction was booked
        /// </summary>
        /// <value>The date the transaction was booked</value>
        [DataMember(Name="bookedDate", EmitDefaultValue=false)]
        public DateTime? BookedDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransactionViewModel {\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  TransactionInformation: ").Append(TransactionInformation).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  BookedDate: ").Append(BookedDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransactionViewModel);
        }

        /// <summary>
        /// Returns true if TransactionViewModel instances are equal
        /// </summary>
        /// <param name="input">Instance of TransactionViewModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransactionViewModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.TransactionInformation == input.TransactionInformation ||
                    (this.TransactionInformation != null &&
                    this.TransactionInformation.Equals(input.TransactionInformation))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.BookedDate == input.BookedDate ||
                    (this.BookedDate != null &&
                    this.BookedDate.Equals(input.BookedDate))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.TransactionInformation != null)
                    hashCode = hashCode * 59 + this.TransactionInformation.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.BookedDate != null)
                    hashCode = hashCode * 59 + this.BookedDate.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
